# Generated by Django 5.2 on 2026-07-20 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(unique=True, verbose_name="Номер столика"),
                ),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("small", "Маленький (2 места)"),
                            ("medium", "Средний (4 места)"),
                            ("large", "Большой (6+ мест)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("seats", models.IntegerField(verbose_name="Количество мест")),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Доступен"),
                ),
                ("pos_x", models.IntegerField(default=0)),
                ("pos_y", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("time_start", models.TimeField(verbose_name="Время начала")),
                (
                    "time_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время окончания"
                    ),
                ),
                ("guests_count", models.IntegerField(verbose_name="Количество гостей")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="bookings.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-created_at"],
            },
        ),
    ]
